apiVersion: v1
kind: ConfigMap
metadata:
  name: default-configuration
  namespace: zproxy-ingress
data:
  listener-http-port: "80"
  listener-https-port: "443"
  listener-error-414: ""
  listener-error-500: ""
  listener-error-501: ""
  listener-error-503: ""
  listener-xhttp: "4"
  listener-rewrite-rocation: "1"
  listener-remove-request-header: ""
  listener-remove-response-header: ""
  listener-add-request-header: ""
  listener-add-response-header: ""
  listener-default-cert: ""
  listener-ciphers: "ALL"
  listener-disable-ssl-protocol: "SSLv3"
  listener-ssl-honor-cipher-order: "1"

  service-https-backends: "false"
  service-strict-transport-security: "21600000"
  service-cookie-name: ""
  service-cookie-path: "/"
  service-cookie-domain: ""
  service-cookie-ttl: "3600"
  service-redirect-url: ""
  service-redirect-code: "302"
  service-redirect-type: "default"
  service-session-type: ""
  service-session-ttl: "120"
  service-session-id: ""
